### ISSUE TITLE
SMTP sink

### ISSUE THREAD

**Issue by gedw99** [RuneRoven/benthosSMTP#1]
Hey @RuneRoven 

this looks like an email sender ?

I’m using benthos and need a smtp sink .

Use case is to have a unique email for each stream . Makes it easy to then do tickets etc because it’s a special email address used for each customer ticket . 

I use benthos / redpanda heaps. Nice little system

**Comment by RuneRoven** [comment]
Yes, this is an email sender only. it is based on net/smtp which is a client library for sending email through a server. It does not have support for receiving emails. That is a complete different story.
